---
# install docker, and pull build-in images on every node
-  hosts: all
   roles:
      - common
   tags:
      - common

-  hosts: all
   roles:
      - docker
   tags:
      - docker

-  hosts: etcd
   roles:
      - etcd
   tags:
      - etcd

-  hosts: haproxy
   roles:
      - haproxy
   tags:
      - haproxy


-  hosts: master
   roles:
      - master
   tags:
      - master

