---
- name: Config systemd
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Enabel etcd systemd
  systemd:
    name: etcd
    enabled: true
    state: restarted
    daemon_reload: yes
