---
- name: Add docker repo
  template:
    src: docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo

- name: Install docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker-engine-{{ docker_version }}"

- name: Create docker etc foler
  file:
    state: directory
    path: /etc/docker

- name: Add aliyun docker mirror
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json


- name: Enabel docker systemd
  systemd:
    name: docker
    enabled: true
    state: restarted
    daemon-reload: yes


- name: Pull buid-in images on ervery node
  include_tasks: docker_images.yaml
